apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-demo
spec:
  template:
    spec:
      containers:
      - name: petclinic-demo
        resources:
          limits:
            memory: 1024Mi