apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-app3-dev
  namespace: argocd
  # to delete the k8s app as well when I delete the application resource.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: my-project
  source:
    repoURL: https://github.com/jingood2/petclinic-multi-env-apps-gitops.git
    targetRevision: main
    path: apps/petclinic-demo/overlays/dev/app3
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=forground
      - PruneLast=true