namespace: dev
images:
- name: MYAPP-IMAGE
  newName: jingood2/petclinic-demo
  newTag: bfafc6e2bf996649333e43300f403b3a3d808238
resources:
- ../../../base
patchesStrategicMerge:
- ./patch/increase_replicas.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: petclinic-app1-dev
  target:
    kind: Deployment
    name: .*
- patch: |-
    - op: replace
      path: /metadata/name
      value: petclinic-app1-svc-dev
  target:
    kind: Service
    name: .*
- patch: |-
    - op: replace
      path: /spec/selector/app
      value: petclinic-app1-dev
  target:
    kind: Service
    name: .*
