namespace: dev
images:
- name: MYAPP-IMAGE
  newName: jingood2/petclinic-demo
  newTag: fc887e6d92f1ff2487d4e72ec2a07a7b94a7e3e1
resources:
- ../../base
- namespace.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- target:
    kind: Deployment
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: petclinic-app2-dev
- target:
    kind: Service
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: petclinic-app2-svc-dev
- target:
    kind: Service
    app: .*
  patch: |-
    - op: replace
      path: /spec/selector/app
      value: petclinic-app2-dev
