namespace: dev
images:
- name: MYAPP-IMAGE
  newName: jingood2/petclinic-demo
  newTag: fdda81a8517944376c5c63d7b235116171a9584b
resources:
- ../../../base
- namespace.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: petclinic-app2-dev
  target:
    kind: Deployment
    name: .*
- patch: |-
    - op: replace
      path: /metadata/name
      value: petclinic-app2-svc-dev
  target:
    kind: Service
    name: .*
- patch: |-
    - op: replace
      path: /spec/selector/app
      value: petclinic-app2-dev
  target:
    kind: Service
    name: .*
